using Microsoft.EntityFrameworkCore;
using WorldRank.Domain.Entities;

namespace WorldRank.Infrastructure.Persistence;

public class WorldRankDbContext : DbContext
{
    public WorldRankDbContext(DbContextOptions<WorldRankDbContext> options) : base(options)
    {
    }

    public DbSet<Player> Players => Set<Player>();
    public DbSet<Wallet> Wallets => Set<Wallet>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Player>(entity =>
        {
            entity.ToTable("Players");
            entity.HasKey(p => p.Id);
            // Ids are generated by the application (GeneratePlayerId), never by the database.
            entity.Property(p => p.Id).ValueGeneratedNever();
            entity.Property(p => p.Name).IsRequired().HasMaxLength(200);
            entity.Property(p => p.Score);
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.ToTable("Wallets");
            entity.HasKey(w => w.Id);
            // Ids are generated by the application (GenerateWalletId), never by the database.
            entity.Property(w => w.Id).ValueGeneratedNever();
            entity.Property(w => w.PlayerId);
            entity.Property(w => w.Currency).HasConversion<string>().HasMaxLength(3);
            entity.Property(w => w.Balance).HasPrecision(18, 2);
            entity.Property(w => w.IsBlocked);
        });
    }

    // WalletService.ApplyFundsStrategy fetches a Wallet via GetWallet() and mutates it
    // externally through a strategy, with no explicit save call afterward (mirrors how
    // the in-memory repository "just persists" by holding the same object reference).
    // Flushing pending changes on dispose keeps that working against a real DB
    // without changing WalletService.
    public override void Dispose()
    {
        if (ChangeTracker.HasChanges())
            SaveChanges();

        base.Dispose();
    }

    public override async ValueTask DisposeAsync()
    {
        if (ChangeTracker.HasChanges())
            await SaveChangesAsync();

        await base.DisposeAsync();
    }
}
