using Microsoft.EntityFrameworkCore;
using WorldRank.Domain.Entities;

namespace WorldRank.Infrastructure.Persistence;

public class WorldRankDbContext : DbContext
{
    public WorldRankDbContext(DbContextOptions<WorldRankDbContext> options) : base(options)
    {
    }

    public DbSet<Player> Players => Set<Player>();
    public DbSet<Wallet> Wallets => Set<Wallet>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Player>(entity =>
        {
            entity.ToTable("Players");
            entity.HasKey(p => p.Id);
            // Ids are generated by the application (GeneratePlayerId), never by the database.
            entity.Property(p => p.Id).ValueGeneratedNever();
            entity.Property(p => p.Name).IsRequired().HasMaxLength(200);
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.ToTable("Wallets");
            entity.HasKey(w => w.Id);
            // Ids are generated by the application (GenerateWalletId), never by the database.
            entity.Property(w => w.Id).ValueGeneratedNever();
            // FK to Player so the DB enforces referential integrity (a wallet can't point to a missing player).
            entity.HasOne<Player>().WithMany().HasForeignKey(w => w.PlayerId);
            entity.Property(w => w.Currency).HasConversion<string>().HasMaxLength(3);
            entity.Property(w => w.Balance).HasPrecision(18, 2);
        });
    }
}
